### ISSUE TITLE
Avoid label collisions?

### ISSUE THREAD

**Issue by alexcroox** [Leaflet/Leaflet.label#128]
Would it be possible to utilise Leaflet.LayerGroup.Collision to avoid labels from overlapping? Is this a common problem?

https://github.com/MazeMap/Leaflet.LayerGroup.Collision

**Comment by IvanSanchez** [comment]
> Would it be possible to utilise Leaflet.LayerGroup.Collision to avoid labels from overlapping?

[Yes.](http://homepage.ntlworld.com./jonathan.deboynepollard/FGA/questions-with-yes-or-no-answers.html)

**Comment by alexcroox** [comment]
Let me re-phrase it, has anyone attempted this before with this plugin before I go editing the core of the collisions plugin to allow collision detection on the label instead of the marker icon.

**Comment by IvanSanchez** [comment]
I developed `LayerGroup.Collision` with `DivIcon`s in mind, so that's why the code just checks for the `_icon` property (which is, I reckon, a complete hack) of a layer when fetching the dimensions of the children layers.

So I didn't check that `LayerGroup.Collision` works properly with `Leaflet.Label` (which uses `_content` instead of `_icon`). 

If you could spend a bit of time making it work, I'd appreciate the pull request :-)

**Comment by IvanSanchez** [comment]
Moved to MazeMap/Leaflet.LayerGroup.Collision#1
